CREATE TABLE REGIONS
  (
    REGION_ID INT,
    REGION_NAME VARCHAR(50),
    PRIMARY KEY (REGION_ID)
  );
  
 CREATE TABLE COUNTRIES
  (
    COUNTRY_ID VARCHAR(50),
    COUNTRY_NAME VARCHAR(50),
    REGION_ID INT,
    PRIMARY KEY (COUNTRY_ID)
  );
 
