

CREATE STORAGE INTEGRATION mysql_cdc_logs
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = 'S3'
ENABLED = TRUE
STORAGE_AWS_ROLE_ARN = ' **** ARN Detail ****'
STORAGE_ALLOWED_LOCATIONS = ('s3://mysql-cdc-logs-bucket-8504/');